name: build-ui

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.3.0
    - name: configure
      run: |
        mkdir build
        cd build
        cmake -D TRACKERBOY_ENABLE_UI=ON -D TRACKERBOY_ENABLE_DEMO=OFF -D TRACKERBOY_ENABLE_TESTS=OFF ..
    - name: build
      run: cmake --build build --config Debug
